### ISSUE TITLE
Switch to serde_json

### ISSUE THREAD

**Issue by nox** [glennw/thread_profiler#1]
There is no need to have multiple different JSON parsers in Servo.

**Comment by dtolnay** [comment]
Strong +1. @glennw would you accept a PR?

**Comment by glennw** [comment]
PRs would be gladly accepted and merged quickly :)

**Comment by dtolnay** [comment]
Thanks for the quick response. Could we get a release for Servo to depend on when you get a chance?

**Comment by glennw** [comment]
@dtolnay Yep - but I just realized that PR didn't have a version bump in ```Cargo.toml``` - we'll need to do that before we can publish the new crate. I can do that on Monday, unless you beat me to it :)
