### ISSUE TITLE
Prepend module path to the profile scope

### ISSUE THREAD

**Issue by zoonage** [glennw/thread_profiler#12]
Whilst working on https://github.com/amethyst/amethyst/issues/503 we thought it would be nice if the module path was pre-prended to the name of the profile scope, this would make troubleshooting easier by making it clearer in the code being profiled as to where the bottleneck is.

My proposition is to update https://github.com/glennw/thread_profiler/blob/master/src/lib.rs#L28 to be something like `let _profile_scope = format!("{}::{}"), module_path!(), $crate::ProfileScope::new($string));`. In this scenario when creating a new profile, `profile_scope!(<str>)` , the `<str>` is optional and acts as a comment for a marker in a function or method. For example;

```rust
// inside some crate called my_crate
fn complex_func() {
    // The profile name for this is my_crate::complex_func
    profile_scope!();
    {
        // The profile name for this is my_crate::complex_func::profile_1
        profile_scope("profile_1");
       // Do some things
    }
    {
        // The profile name for this is my_crate::complex_func::profile_2
        profile_scope("profile_2");
        // Do some other things
    }
}
```

**Comment by glennw** [comment]
Sounds good to me!

**Comment by zoonage** [comment]
I'll put in a PR within the next few days for this, I've written it up, but would like to do a quick test first
