### ISSUE TITLE
Remove thread_profiler gating feature

### ISSUE THREAD

**Issue by kvark** [glennw/thread_profiler#9]
I believe this is non-idiomatic. What was the reason for it?
I think, WebRender should just have `thread_profiler` as a feature and optional dependency at the same time.

**Comment by zoonage** [comment]
Agreed, from what I've seen the attributes are just set inside the calling crate, which is a lot easier.

**Comment by zoonage** [comment]
Created #14 to remove these @kvark is this what you were looking for?
